### ISSUE TITLE
the pre-filled PAW file could not be opened.

### ISSUE THREAD

**Issue by Agenric** [fastlane/itc-api-docs#24] opened 2017-08-22 12:59 UTC
I downloaded this file, but Paw can't open it. Who can help me.

![image](https://user-images.githubusercontent.com/11513056/29566519-b733f1ae-877c-11e7-8421-16791c9274df.png)

**Comment by ignazioc** [comment] 2017-09-14 11:09
same here

**Comment by KrauseFx** [comment] 2017-09-17 14:46
Duplicate of https://github.com/fastlane/itc-api-docs/issues/20

**Closed by KrauseFx** 2017-09-17 14:46 UTC
